import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="min-h-screen lg:w-[100ch] lg:border-e flex flex-col">
          <header>
            <h1 className="text-8xl">Dither's Blog</h1>
          </header>
          <main className="pt-12 p-4 md:max-w-[80ch] mx-auto flex-grow">
            {children}
          </main>
          <footer className="p-12">
            <h2 className="text-3xl">Contact Me</h2>
            <ul className="list-disc px-9">
              {[
                {
                  title: "Email",
                  href: "mailto:hi@dither.dev",
                  display: "hi@dither.dev",
                },
                {
                  title: "Twitter",
                  href: "https://twitter.com/ditherwither",
                  display: "@ditherwither",
                },
                {
                  title: "GitHub",
                  href: "https://github.com/ditherwither",
                  display: "@ditherwither",
                },
                {
                  title: "Discord",
                  href: "https://discord.com/users/723414810644971572",
                  display: "@ditherwither",
                },
              ].map((contact, i) => (
                <ContactItem key={i} {...contact} />
              ))}
            </ul>
          </footer>
        </div>
      </body>
    </html>
  );
}

function ContactItem({
  title,
  href,
  display,
}: Readonly<{
  title: string;
  href: string;
  display: string;
}>) {
  return (
    <li>
      {title + ": "}
      <a href={href} className="underline font-bold">
        {display}
      </a>
    </li>
  );
}
