import type { Metadata } from "next";
import "./globals.css";
import { inter, interTight } from "~/fonts";

export const metadata: Metadata = {
  title: "DitherWither",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${inter.className} max-w-[120ch] bg-gradient-to-b from-slate-900 to-slate-700`}
      >
        <div className="min-h-screen flex flex-col">
          <header className="p-12">
            <h1
              className={`text-6xl md:text-8xl text-transparent bg-clip-text bg-gradient-to-r bg-linear-65 from-purple-500 to-pink-500 font-semibold ${interTight.className}`}
            >
              DitherWither
            </h1>
            <p className="text-3xl text-neutral-400">
              Full-Stack Web Developer
            </p>
          </header>
          <main className="p-4 md:max-w-[80ch] mx-auto flex-grow">
            {children}
          </main>
          <footer className="p-12">
            <h2 className="text-3xl">Contact Me</h2>
            <ul className="list-disc px-9">
              {[
                {
                  title: "Email",
                  href: "mailto:hi@dither.dev",
                  display: "hi@dither.dev",
                },
                {
                  title: "Twitter",
                  href: "https://twitter.com/ditherwither",
                  display: "@ditherwither",
                },
                {
                  title: "GitHub",
                  href: "https://github.com/ditherwither",
                  display: "@ditherwither",
                },
                {
                  title: "Discord",
                  href: "https://discord.com/users/723414810644971572",
                  display: "@ditherwither",
                },
                {
                  title: "LinkedIn",
                  href: "https://www.linkedin.com/in/ditherwither",
                  display: "ditherwither",
                },
              ].map((contact) => (
                <ContactItem key={contact.href} {...contact} />
              ))}
            </ul>
          </footer>
        </div>
      </body>
    </html>
  );
}

function ContactItem({
  title,
  href,
  display,
}: Readonly<{
  title: string;
  href: string;
  display: string;
}>) {
  return (
    <li>
      {`${title}: `}
      <a href={href} className="underline font-bold">
        {display}
      </a>
    </li>
  );
}
